# Generated by Django 5.2.4 on 2025-07-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей сервиса"),
                ]
            },
        ),
    ]
