# Generated by Django 5.2.3 on 2025-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='client',
            new_name='clients',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(verbose_name='Конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начало рассылки'),
        ),
    ]
