# Generated by Django 5.2.4 on 2025-07-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_attempt_owner_alter_client_owner_alter_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
