# Generated by Django 5.2.4 on 2025-07-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_client_options_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Может просматривать все рассылки"),
                    ("can_toggle_mailing", "Может отключать/включать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
